/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package core

import (
	"strings"

	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	carbitev1alpha1 "github.com/NVIDIA/bare-metal-manager-operator/api/v1alpha1"
)

// BuildCasbinPolicyConfigMap creates the Casbin RBAC policy ConfigMap.
// The policy is dynamically generated based on enabled services.
func BuildCasbinPolicyConfigMap(deployment *carbitev1alpha1.CarbideDeployment, namespace string) *corev1.ConfigMap {
	var lines []string

	lines = append(lines,
		"# Casbin RBAC policy - auto-generated by carbide-operator",
		"",
		"# Map SPIFFE service IDs to roles",
		"g, spiffe-service-id/carbide-dhcp, carbide-dhcp",
		"g, spiffe-service-id/carbide-dns, carbide-dns",
		"g, spiffe-machine-id, machine",
		"",
		"# DHCP and DNS access",
		"p, carbide-dhcp, forge/DiscoverDhcp",
		"p, carbide-dns, forge/LookupRecord",
		"",
		"# Trusted certificate access",
		"p, trusted-certificate, forge/*",
		"",
		"# Anonymous access to safe endpoints",
		"p, anonymous, forge/Version",
	)

	// Add RLA policy if enabled
	if deployment.Spec.Core.RLA != nil && deployment.Spec.Core.RLA.Enabled {
		lines = append(lines,
			"",
			"# RLA service access",
			"g, spiffe-service-id/carbide-rla, carbide-rla",
			"p, carbide-rla, forge/*",
		)
	}

	// Add PSM policy if enabled
	if deployment.Spec.Core.PSM != nil && deployment.Spec.Core.PSM.Enabled {
		lines = append(lines,
			"",
			"# PSM service access",
			"g, spiffe-service-id/carbide-psm, carbide-psm",
			"p, carbide-psm, forge/*",
		)
	}

	casbinPolicy := strings.Join(lines, "\n") + "\n"

	return &corev1.ConfigMap{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "casbin-policy",
			Namespace: namespace,
			Labels: map[string]string{
				"app.kubernetes.io/name":       "casbin-policy",
				"app.kubernetes.io/part-of":    "carbide-core",
				"app.kubernetes.io/managed-by": "carbide-operator",
			},
		},
		Data: map[string]string{
			"casbin-policy.csv": casbinPolicy,
		},
	}
}
