name: E2E Tests

on:
  pull_request:
  workflow_dispatch:

env:
  IMG: localhost/nvidia-carbide-operator:e2e
  DOCKERFILE: Dockerfile.ci
  CERT_MANAGER_INSTALL_SKIP: "true"

jobs:
  test-e2e:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install the latest version of kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-$(go env GOARCH)
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Run E2E tests
        run: |
          go mod tidy
          make test-e2e
