name: E2E Tests

on:
  pull_request:
  workflow_dispatch:

env:
  IMG: localhost/nvidia-carbide-operator:e2e
  DOCKERFILE: Dockerfile.ci
  CERT_MANAGER_INSTALL_SKIP: "false"
  SPIRE_INSTALL_SKIP: "false"

jobs:
  test-e2e:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    env:
      CORE_REPO_PATH: ${{ github.workspace }}/bare-metal-manager-core
      REST_REPO_PATH: ${{ github.workspace }}/bare-metal-manager-rest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Clone bare-metal-manager-core
        uses: actions/checkout@v4
        with:
          repository: NVIDIA/bare-metal-manager-core
          path: bare-metal-manager-core

      - name: Clone bare-metal-manager-rest
        uses: actions/checkout@v4
        with:
          repository: NVIDIA/bare-metal-manager-rest
          path: bare-metal-manager-rest

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Increase inotify limits for Carbide stack
        run: |
          sudo sysctl -w fs.inotify.max_user_instances=512
          sudo sysctl -w fs.inotify.max_user_watches=1048576

      - name: Install the latest version of kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-$(go env GOARCH)
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Run E2E tests
        run: |
          go mod tidy
          make test-e2e

      - name: Cleanup
        if: always()
        run: |
          make cleanup-test-e2e || true
